image: gitpod/workspace-full

tasks:
  - name: nasm
    before: sudo apt install binutils 
    init:  sudo apt install nasm
    command: >
      source setup/.assemble.sh
      printf "\n Nasm is good to go on this workspace"
  
  - name: workspace
