image: gitpod/workspace-mongodb
ports:
  - port: 27017 # mongodb

tasks:
  - name: db
    # starting mongo in background, so it doesn't block prebuilds
    before: >
      mkdir -p /workspace/data &&
      (mongod --dbpath /workspace/data &)
 
