image: gitpod/workspace-mongodb
ports:
  - port: 27017 # mongodb
    onOpen: ignore

tasks:
  - name: db
    # starting mongo in background, so it doesn't block prebuilds
    before: >
      mkdir -p /workspace/data &&
      (mongod --dbpath /workspace/data &)

  - name: nasm
    command: sudo apt install nasm && sudo apt install binutils && source setup/.assemble.sh
